# Generated by Django 6.0.3 on 2026-03-18 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleProfile',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('mileage', models.FloatField(help_text='km per liter')),
                ('idle_consumption', models.FloatField(help_text='liters per hour')),
            ],
        ),
    ]
