# Generated by Django 6.0.3 on 2026-03-31 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicleprofile',
            name='vehicle_type',
            field=models.CharField(choices=[('car', 'Car (Generic)'), ('sedan', 'Sedan'), ('suv', 'SUV'), ('bike', 'Bike'), ('truck', 'Truck'), ('bus', 'Bus'), ('other', 'Other')], default='car', max_length=20),
        ),
        migrations.AlterField(
            model_name='vehicleprofile',
            name='idle_consumption',
            field=models.FloatField(blank=True, help_text='liters per hour', null=True),
        ),
        migrations.AlterField(
            model_name='vehicleprofile',
            name='mileage',
            field=models.FloatField(blank=True, help_text='km per liter', null=True),
        ),
    ]
