# Generated by Django 6.0.3 on 2026-04-01 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routing', '0002_vehicleprofile_vehicle_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_lat', models.FloatField()),
                ('start_lng', models.FloatField()),
                ('end_lat', models.FloatField()),
                ('end_lng', models.FloatField()),
                ('city', models.CharField(default='Lahore, Pakistan', max_length=100)),
                ('mileage', models.FloatField(help_text='km per liter')),
                ('idle_consumption', models.FloatField(help_text='liters per hour')),
                ('fuel_price', models.FloatField(default=280)),
                ('fuel_route', models.JSONField()),
                ('shortest_route', models.JSONField()),
                ('fuel_cost', models.FloatField()),
                ('fuel_distance', models.FloatField()),
                ('fuel_time', models.FloatField()),
                ('fuel_cost_pkr', models.FloatField()),
                ('shortest_fuel_cost', models.FloatField()),
                ('shortest_distance', models.FloatField()),
                ('shortest_time', models.FloatField()),
                ('shortest_cost_pkr', models.FloatField()),
                ('fuel_saved', models.FloatField()),
                ('cost_saved', models.FloatField()),
                ('time_saved', models.FloatField()),
                ('distance_saved', models.FloatField()),
                ('cache_status', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
